title: product
$id: objectDefs/product
$schema: 'http://json-schema.org/draft-07/schema'
type: object
properties:
  "manufacturer":
    $ref: MXobject_organization
    $comment: |
      []Debbie: should organization be used here?
  
  "model":
    type: string
    description: this is the full model name, which may include a brand name, model name, and sub-model name concatenated into a single string of text. 
    $comment: Model denotes configuration that are set when the product come out of the production process. 

  "model year":
    type: string
    
  "catalog configuration code":
    type: string
    description: A text the communicates the exact configuration of the asset, within a pre-defined configuration space.
    $comment: configuration code denotes configurations that would be made only after the purchasing customer have specifies them. This information would be used by human for ordering replacements, so if the code also contains manufacturer or model information, it is okay for the purpose. The key attribute we need here is completeness.

  ################################## RULES ##################################

  required: # RULE IN ENGLISH: these data fields that are unconditionally required on every record
  - "manufacturer"
  - "model"
  